[package]
name = "memory_practice"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.29"
rusqlite = { version = "0.32", features = ["bundled", "chrono"] }
refinery = { version = "0.8", features = ["rusqlite"] }
rand = "0.8"
chrono = "0.4"
sra = "0.1"
log = "0.4"
env_logger = "0.11"
